### ISSUE TITLE
OverflowError: iteration value is too great

### ISSUE THREAD

**Issue by ultra-azu** [asmw/andOTP-decrypt#13]
Title says it all, here's all the output:

```
andOTP AES passphrase:
Traceback (most recent call last):
  File "/home/me/.local/bin//andotp_decrypt", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.7/site-packages/andotp_decrypt.py", line 102, in main
    print(decrypt_aes_new_format(password, input_file, debug))
  File "/home/me/.local/lib/python3.7/site-packages/andotp_decrypt.py", line 62, in decrypt_aes_new_format
    pbkdf2_key = hashlib.pbkdf2_hmac('sha1', password, salt, iterations, 32)
OverflowError: iteration value is too great.
```

I'll provide any other information possible.

**Comment by ultra-azu** [comment]
Looks like I mistook this tool as being able to read the andOTP actual data rather than the backup. Oops!

**Comment by asmw** [comment]
@Ultracoolguy just out of curiosity, you ran the script on an unencrypted JSON export?
